mysql:
  host: 127.0.0.1
  port: 3306
  db: myblog_db
  user: root
  password: 010226
  log_level: dev
logger:
  level: info
  prefix: '[myblog]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: "0.0.0.0"
  port: 8099
  env: dev